### ISSUE TITLE
Clone still fails when cloning an object that does not have setters defined on some of its properties

### ISSUE THREAD

**Issue by tukusejssirs** [pvorb/clone#117]
Related: #91

---

When running tests, this test case fails on `v2.1.2` (ab17eb6):

```js
✖ clone should not fail when cloning an object that does not have setters defined on some of its properties

ReferenceError: x is not defined
    at Object.get [as x] ({repo_root}/test.js:695:7)
    at _clone ({repo_root}/clone.js:156:33)
    at clone ({repo_root}/clone.js:210:10)
    at {repo_root}/test.js:701:20
    at _throws ({repo_root}/node_modules/nodeunit/lib/assert.js:320:5)
    at assert.doesNotThrow ({repo_root}/node_modules/nodeunit/lib/assert.js:351:11)
    at Object.doesNotThrow ({repo_root}/node_modules/nodeunit/lib/types.js:83:39)
    at Object.exports.clone should not fail when cloning an object that does not have setters defined on some of its properties ({repo_root}/test.js:699:8)
    at Object.<anonymous> ({repo_root}/node_modules/nodeunit/lib/core.js:236:16)
    at {repo_root}/node_modules/nodeunit/lib/core.js:236:16
    at Object.exports.runTest ({repo_root}/node_modules/nodeunit/lib/core.js:70:9)
    at {repo_root}/node_modules/nodeunit/lib/core.js:118:25
    at {repo_root}/node_modules/nodeunit/deps/async.js:513:13
    at iterate ({repo_root}/node_modules/nodeunit/deps/async.js:123:13)
    at {repo_root}/node_modules/nodeunit/deps/async.js:134:25
    at {repo_root}/node_modules/nodeunit/deps/async.js:515:17
```

Possible test fix:

```diff
@@ -689,10 +689,10 @@ exports["clone should not fail when cloning an object that does not have setters
   test.expect(1);
 
   //init an object with only a getter defined
-  var source = { x: null };
-  Object.defineProperty(source, 'x', { 
-    get: function() { 
-      return x; 
+  var source = { x: null, y: true };
+  Object.defineProperty(source, 'x', {
+    get: function() {
+      return y;
     }
   });
```

---

However, fixing the test itself does not solve the underlining issue, as I run into this issue when using Nest + MikroORM + `nest-mqtt` (see mikro-orm/mikro-orm#2597).

---

As for [this code comment](https://github.com/pvorb/clone/blob/master/clone.js#L168-L169), I even tried to set `compilerOptions.strict` to `false`, but I still get the same error.

I use `typescript` `v4.5.4` if that matters.

**Comment by tukusejssirs** [comment]
Aaah, sorry, it _is_ actually fixed, however [`defaults`](https://github.com/tmpvar/defaults#readme) still uses `clone` `v1`, as it is indirectly required by Nest (see below).

Sorry for the noise! :wink:

```ts
defaults@1.0.3 dev
node_modules/defaults
  defaults@"^1.0.3" from wcwidth@1.0.1
  node_modules/wcwidth
    wcwidth@"^1.0.1" from ora@5.4.1
    node_modules/ora
      ora@"5.4.1" from @angular-devkit/schematics@13.1.1
      node_modules/@angular-devkit/schematics
        @angular-devkit/schematics@"13.1.1" from @angular-devkit/schematics-cli@13.1.1
        node_modules/@angular-devkit/schematics-cli
          @angular-devkit/schematics-cli@"13.1.1" from @nestjs/cli@8.1.6
          node_modules/@nestjs/cli
            dev @nestjs/cli@"^8.1.6" from the root project
        @angular-devkit/schematics@"13.1.1" from @nestjs/cli@8.1.6
        node_modules/@nestjs/cli
          dev @nestjs/cli@"^8.1.6" from the root project
      ora@"^5.4.1" from inquirer@8.2.0
      node_modules/@angular-devkit/schematics-cli/node_modules/inquirer
        inquirer@"8.2.0" from @angular-devkit/schematics-cli@13.1.1
        node_modules/@angular-devkit/schematics-cli
          @angular-devkit/schematics-cli@"13.1.1" from @nestjs/cli@8.1.6
          node_modules/@nestjs/cli
            dev @nestjs/cli@"^8.1.6" from the root project
      ora@"5.4.1" from @nestjs/cli@8.1.6
      node_modules/@nestjs/cli
        dev @nestjs/cli@"^8.1.6" from the root project
      ora@"5.4.1" from @angular-devkit/schematics@13.0.2
      node_modules/@nestjs/schematics/node_modules/@angular-devkit/schematics
        @angular-devkit/schematics@"13.0.2" from @nestjs/schematics@8.0.5
        node_modules/@nestjs/schematics
          @nestjs/schematics@"^8.0.3" from @nestjs/cli@8.1.6
          node_modules/@nestjs/cli
            dev @nestjs/cli@"^8.1.6" from the root project
```
